WITH P AS(
    SELECT B.BOOK_ID, B.PRICE, SUM(S.SALES) TOTAL, B.PRICE * SUM(S.SALES) TOTAL_SALES FROM BOOK B JOIN
    BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE BETWEEN TO_DATE('2022-01-01','YYYY-MM-DD') AND TO_DATE('2022-01-31','YYYY-MM-DD')
    GROUP BY B.BOOK_ID, B.PRICE
),
Q AS(
    SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, A.AUTHOR_NAME FROM BOOK B
    JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
)
SELECT Q.AUTHOR_ID, Q.AUTHOR_NAME, Q.CATEGORY, SUM(P.TOTAL_SALES) FROM P JOIN Q ON Q.BOOK_ID = P.BOOK_ID
    GROUP BY Q.AUTHOR_ID, Q.AUTHOR_NAME, Q.CATEGORY
    ORDER BY Q.AUTHOR_ID, Q.CATEGORY DESC;