-- 코드를 입력하세요
WITH T AS(
    SELECT WRITER_ID, COUNT(*) C FROM USED_GOODS_BOARD GROUP BY WRITER_ID
)

SELECT U.USER_ID, U.NICKNAME, U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 AS 전체주소, 
    SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8, 4) AS 전화번호
    FROM USED_GOODS_USER U,T WHERE U.USER_ID = T.WRITER_ID AND T.C >=3 ORDER BY U.USER_ID DESC;

