WITH TOTAL AS ( -- 2021년 가입자 수
    SELECT COUNT(*)  AS CNT
      FROM USER_INFO A
     WHERE A.JOINED LIKE '2021%'
)       
SELECT YEAR(B.SALES_DATE) AS YEAR
     , MONTH(B.SALES_DATE) AS MON
     , COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS
     , ROUND((COUNT(DISTINCT B.USER_ID)/T.CNT), 1) AS PUCHASED_RATIO
  FROM ONLINE_SALE B
     , USER_INFO A
     , TOTAL T
 WHERE B.USER_ID = A.USER_ID
   AND YEAR(A.JOINED) LIKE '2021%'
 GROUP BY YEAR, MON
 ORDER BY YEAR, MON