

SELECT A.FLAVOR FROM FIRST_HALF A JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM JULY GROUP BY FLAVOR) C 
    ON A.FLAVOR = C.FLAVOR
    ORDER BY A.TOTAL_ORDER + C.TOTAL_ORDER DESC
    LIMIT 3;

;