-- 코드를 입력하세요
WITH A AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) S FROM FIRST_HALF GROUP BY FLAVOR
),
B AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) SU FROM JULY GROUP BY FLAVOR
)
SELECT A.FLAVOR FROM A JOIN B ON A.FLAVOR = B.FLAVOR
    ORDER BY A.S+B.SU DESC
    FETCH FIRST 3 ROWS ONLY;