-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
),
T AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT 
    FROM ANIMAL_OUTS 
    GROUP BY HOUR(DATETIME)
)
SELECT 
    H.HOUR,
    IFNULL(T.COUNT, 0) AS COUNT
FROM HOURS H
LEFT JOIN T ON H.HOUR = T.HOUR
ORDER BY H.HOUR;