-- 코드를 입력하세요
WITH T AS (
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES FROM USED_GOODS_BOARD
            WHERE STATUS = 'DONE' GROUP BY WRITER_ID
            HAVING SUM(PRICE)>=700000
)
SELECT U.USER_ID, U.NICKNAME, T.TOTAL_SALES FROM USED_GOODS_USER U
    JOIN T ON T.WRITER_ID = U.USER_ID
    ORDER BY T.TOTAL_SALES;

