-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE 
    FROM MEMBER_PROFILE A
    JOIN (
        SELECT C.MEMBER_ID, C.REVIEW_TEXT, C.REVIEW_DATE FROM REST_REVIEW C
            WHERE C.MEMBER_ID = (
                SELECT MEMBER_ID FROM REST_REVIEW
                GROUP BY MEMBER_ID
                ORDER BY COUNT(*) DESC
                LIMIT 1
            )
            ORDER BY C.REVIEW_DATE, C.REVIEW_TEXT
        ) B ON A.MEMBER_ID = B.MEMBER_ID
        ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT; 
    


