SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') PUBLISHED_DATE FROM BOOK
    WHERE TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') BETWEEN '2021-01-01' AND '2021-12-31'
    AND CATEGORY = '인문'
    ORDER BY PUBLISHED_DATE;
    