-- 코드를 입력하세요
WITH T AS(
    SELECT MAX(VIEWS) V FROM USED_GOODS_BOARD
)
SELECT '/home/grep/src/' || B.BOARD_ID || '/' || F.FILE_ID || F.FILE_NAME ||  F.FILE_EXT FILE_PATH 
    FROM USED_GOODS_FILE F
    JOIN USED_GOODS_BOARD B ON F.BOARD_ID = B.BOARD_ID
    JOIN T ON B.VIEWS = T.V
    ORDER BY F.FILE_ID DESC;